# Application Info
info:
  name: Bills
  description: Bills
  version: 1.0

server:
  port: 8080
  context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: trot
    password: trot
    driver-class-name: org.postgresql.Driver
    schema: app

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: app
        hbm2ddl.auto: create
        hibernate.show_sql: false
        hibernate.format_sql: false

logging:
  level:
    matchingstore: 'INFO'